repos:
  - repo: local
    hooks:
      - id: verify-checks
        name: Verify dev check has been run
        entry: .githooks/verify-checks
        language: system
        stages: [commit, merge-commit, push]
        pass_filenames: false
